### ISSUE TITLE
Broken with aomenc

### ISSUE THREAD

**Issue by drizzt** [gianni-rosato/rav1ator-cli#4]
[build.log](https://github.com/gianni-rosato/rav1ator-cli/files/14833982/build.log)

**Comment by drizzt** [comment]
I didn't update binaries

**Comment by pat-e** [comment]
SOLVED:
For everyone else reading and having same issue:

Have you checked that you use the "included" AomEnc - Psy - fork?
The script has a function to update the binaries with " -b" to download the new specialized binaries and copy them automatic into the /usr/bin - folder.

**Comment by gianni-rosato** [comment]
@pat-e is correct; as of right now, rAV1ator CLI's aomenc settings are *only* compatible with the aom-av1-lavish community fork, which is shipped in the binaries.
